language: elixir

elixir:
  - 1.9.2

otp_release:
  - "22.0"

services:
  - postgresql

before_script:
  - psql -c 'create database gen_queue_oban_test;' -U postgres

env:
  - MIX_ENV=test

script:
  - mix test
